-- ============================================================
-- SGA | Passo 2 de 3 - AUDITORIA (rastreabilidade)
-- Registra quem fez o quê: INSERT/UPDATE/DELETE em todas as
-- tabelas de negocio + LOGIN/LOGOUT registrados pelo front-end.
--
-- Onde executar: Supabase Dashboard > SQL Editor > New query > Run.
-- Pode ser executado mais de uma vez (idempotente).
-- Ordem: 01_perfis.sql -> 02_auditoria.sql -> 03_usuarios_rpc.sql
-- ============================================================

-- ------------------------------------------------------------
-- Tabela de auditoria
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.auditoria (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id     uuid,
  usuario_email  text,
  usuario_perfil text,
  tabela         text NOT NULL,
  acao           text NOT NULL CHECK (acao IN ('INSERT', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT')),
  registro_id    text,
  dados_antes    jsonb,
  dados_depois   jsonb,
  criado_em      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_auditoria_criado_em ON public.auditoria (criado_em DESC);
CREATE INDEX IF NOT EXISTS idx_auditoria_usuario   ON public.auditoria (usuario_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_tabela    ON public.auditoria (tabela, acao);

-- ------------------------------------------------------------
-- Funcao acionada pelos triggers (SECURITY DEFINER: escreve na
-- auditoria mesmo quando o cliente nao tem INSERT no banco)
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_auditoria() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE
  v_uid     uuid    := auth.uid();
  v_email   text;
  v_perfil  text;
  v_antes   jsonb;
  v_depois  jsonb;
  v_registro text;
BEGIN
  -- Quem executou a operacao
  IF v_uid IS NOT NULL THEN
    SELECT email, perfil INTO v_email, v_perfil
      FROM public.usuarios
     WHERE id = v_uid;
  END IF;

  -- Fallback: e-mail do token JWT quando nao ha linha em usuarios
  IF v_email IS NULL THEN
    BEGIN
      v_email := current_setting('request.jwt.claims', true)::jsonb ->> 'email';
    EXCEPTION WHEN others THEN
      v_email := NULL;
    END;
  END IF;

  IF TG_OP = 'INSERT' THEN
    v_antes   := NULL;
    v_depois  := to_jsonb(NEW);
    v_registro := to_jsonb(NEW) ->> 'id';
  ELSIF TG_OP = 'UPDATE' THEN
    v_antes   := to_jsonb(OLD);
    v_depois  := to_jsonb(NEW);
    v_registro := to_jsonb(NEW) ->> 'id';
  ELSE
    v_antes   := to_jsonb(OLD);
    v_depois  := NULL;
    v_registro := to_jsonb(OLD) ->> 'id';
  END IF;

  INSERT INTO public.auditoria
    (usuario_id, usuario_email, usuario_perfil, tabela, acao, registro_id, dados_antes, dados_depois)
  VALUES
    (v_uid, v_email, v_perfil, TG_TABLE_NAME, TG_OP, v_registro, v_antes, v_depois);

  RETURN NULL;
END;
$$;

-- ------------------------------------------------------------
-- Triggers em todas as tabelas de negocio (idempotente)
-- ------------------------------------------------------------
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'usuarios', 'documentos', 'emprestimos', 'salas',
    'estantes', 'prateleiras', 'caixas', 'arquivos_digitais'
  ] LOOP
    IF to_regclass('public.' || t) IS NULL THEN
      RAISE NOTICE 'Tabela inexistente, ignorada: public.%', t;
      CONTINUE;
    END IF;

    EXECUTE format('DROP TRIGGER IF EXISTS trg_auditoria ON public.%I', t);
    EXECUTE format(
      'CREATE TRIGGER trg_auditoria AFTER INSERT OR UPDATE OR DELETE ON public.%I '
      || 'FOR EACH ROW EXECUTE FUNCTION public.fn_auditoria()', t);
  END LOOP;
END $$;

-- ------------------------------------------------------------
-- RLS: leitura apenas para administrador.
-- INSERT: somente o evento de LOGIN/LOGOUT do proprio usuario
--         (o front registra a autenticacao; o Auth nao dispara
--         trigger em tabela publica). UPDATE/DELETE: nenhum.
-- ------------------------------------------------------------
ALTER TABLE public.auditoria ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE p RECORD;
BEGIN
  FOR p IN
    SELECT policyname FROM pg_policies
     WHERE schemaname = 'public' AND tablename = 'auditoria'
  LOOP
    EXECUTE format('DROP POLICY %I ON public.auditoria', p.policyname);
  END LOOP;
END $$;

CREATE POLICY auditoria_select ON public.auditoria
  FOR SELECT TO authenticated
  USING (public.sga_perfil() = 'admin');

CREATE POLICY auditoria_insert_eventos ON public.auditoria
  FOR INSERT TO authenticated
  WITH CHECK (
    tabela = 'auth'
    AND acao IN ('LOGIN', 'LOGOUT')
    AND usuario_id = auth.uid()
  );

-- A anon key e publica: anonim nao pode ler nem escrever auditoria
REVOKE ALL ON public.auditoria FROM anon;
-- authenticated: so SELECT (limitado pela policy de admin) e INSERT
-- dos proprios eventos de LOGIN/LOGOUT. TRUNCATE nao passa por RLS,
-- por isso e revogado explicitamente (evita apagar evidencias).
REVOKE UPDATE, DELETE, TRUNCATE ON public.auditoria FROM authenticated, anon;
GRANT SELECT, INSERT ON public.auditoria TO authenticated;
GRANT USAGE ON SEQUENCE public.auditoria_id_seq TO authenticated;
