-- ============================================================
-- SGA | 10_corredores.sql
-- Nova secao "Novo Corredor" na tela Cadastro > Salas de Arquivo.
-- Mesma logica da estante: codigo pertencente a uma SALA, com
-- descricao, RLS e trigger de auditoria. Tambem cria o vinculo
-- estante <-> corredor (estantes.corredor_id).
--
-- Onde executar: Supabase Dashboard > SQL Editor > New query > Run.
-- Idempotente: pode ser executado mais de uma vez (cria a tabela
-- se nao existir; se ja existir SEM a coluna sala_id, adiciona).
-- Ordem: apos todos os arquivos anteriores (01 -> 09).
-- ============================================================

-- ------------------------------------------------------------
-- 1) Tabela (o tipo de sala_id espelha o tipo real de salas.id)
-- ------------------------------------------------------------
DO $$
DECLARE
  v_tipo   text;
  v_id_def text;
BEGIN
  IF to_regclass('public.salas') IS NULL THEN
    RAISE EXCEPTION 'Tabela public.salas nao existe. Rode antes os arquivos 01-09.';
  END IF;

  SELECT format_type(a.atttypid, a.atttypmod)
    INTO v_tipo
    FROM pg_attribute a
   WHERE a.attrelid = 'public.salas'::regclass
     AND a.attname = 'id'
     AND a.attnum > 0 AND NOT a.attisdropped;

  IF v_tipo = 'uuid' THEN
    v_id_def := 'uuid PRIMARY KEY DEFAULT gen_random_uuid()';
  ELSIF v_tipo IN ('bigint', 'integer', 'smallint') THEN
    v_id_def := format('%s GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', v_tipo);
  ELSE
    v_id_def := format('%s PRIMARY KEY', v_tipo);
  END IF;

  IF to_regclass('public.corredores') IS NULL THEN
    EXECUTE format(
      'CREATE TABLE public.corredores ('
      || '  %s,'
      || '  codigo     text NOT NULL,'
      || '  sala_id    %s NOT NULL REFERENCES public.salas(id),'
      || '  descricao  text,'
      || '  created_at timestamptz NOT NULL DEFAULT now())',
      v_id_def, v_tipo);
  ELSIF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = 'corredores' AND column_name = 'sala_id'
  ) THEN
    EXECUTE format('ALTER TABLE public.corredores ADD COLUMN sala_id %s NOT NULL REFERENCES public.salas(id)', v_tipo);
  END IF;
END $$;

-- ------------------------------------------------------------
-- 2) RLS: 4 politicas TO authenticated (mesmo padrao do 04)
-- ------------------------------------------------------------
ALTER TABLE public.corredores ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE p RECORD;
BEGIN
  FOR p IN
    SELECT policyname FROM pg_policies
     WHERE schemaname = 'public' AND tablename = 'corredores'
  LOOP
    EXECUTE format('DROP POLICY %I ON public.corredores', p.policyname);
  END LOOP;
END $$;

CREATE POLICY documentos_select ON public.corredores
  FOR SELECT TO authenticated USING (true);
CREATE POLICY documentos_insert ON public.corredores
  FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY documentos_update ON public.corredores
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY documentos_delete ON public.corredores
  FOR DELETE TO authenticated USING (true);

-- A anon key e publica: anon NUNCA toca na tabela
REVOKE ALL ON public.corredores FROM anon;
REVOKE TRUNCATE ON public.corredores FROM authenticated;

-- ------------------------------------------------------------
-- 3) Auditoria (mesmo padrao do 02)
-- ------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_auditoria ON public.corredores;
CREATE TRIGGER trg_auditoria
  AFTER INSERT OR UPDATE OR DELETE ON public.corredores
  FOR EACH ROW EXECUTE FUNCTION public.fn_auditoria();

-- ------------------------------------------------------------
-- 4) Vinculo estante <-> corredor (coluna nova em estantes)
--    Nullable: estantes ja cadastradas ficam com NULL.
-- ------------------------------------------------------------
DO $$
DECLARE v_tipo text;
BEGIN
  IF to_regclass('public.estantes') IS NULL THEN
    RAISE NOTICE 'Tabela public.estantes inexistente, coluna corredor_id ignorada.';
    RETURN;
  END IF;

  SELECT format_type(a.atttypid, a.atttypmod)
    INTO v_tipo
    FROM pg_attribute a
   WHERE a.attrelid = 'public.corredores'::regclass
     AND a.attname = 'id'
     AND a.attnum > 0 AND NOT a.attisdropped;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = 'estantes' AND column_name = 'corredor_id'
  ) THEN
    EXECUTE format('ALTER TABLE public.estantes ADD COLUMN corredor_id %s REFERENCES public.corredores(id)', v_tipo);
  END IF;
END $$;

-- ------------------------------------------------------------
-- VERIFICACAO FINAL
-- ------------------------------------------------------------
-- a) Colunas (esperado: id, codigo, sala_id, descricao, created_at)
SELECT column_name, data_type, is_nullable
  FROM information_schema.columns
 WHERE table_schema = 'public' AND table_name = 'corredores'
 ORDER BY ordinal_position;

-- b) Policies (esperado: 4 linhas "documentos_*" TO authenticated)
SELECT tablename, policyname, cmd, roles
  FROM pg_policies
 WHERE schemaname = 'public' AND tablename = 'corredores'
 ORDER BY policyname;

-- c) Grants do anon (esperado: ZERO linhas)
SELECT grantee, table_name, privilege_type
  FROM information_schema.role_table_grants
 WHERE table_schema = 'public' AND table_name = 'corredores'
   AND grantee = 'anon';

-- d) RLS ativo (esperado: true)
SELECT c.relname AS tabela, c.relrowsecurity AS rls
  FROM pg_class c
 WHERE c.relnamespace = 'public'::regnamespace
   AND c.relkind = 'r' AND c.relname = 'corredores';
